char* function_prelude = "\t.text\n"
   "\t.globl\t%s\n"
   "\t.def\t%s;\t.scl"
   "\t2;\t.type\t32;\t.e"
   "ndef\n"
   "\t.seh_proc\t%s\n"
   ""
   "%s:\n"
   "\tpushq\t%%rbp\n"
   "\tmovq\t%%rsp, %%rbp\n"
   "\tsubq\t$32, %%rsp\n";