char* printf_def = "\t.text\n"
   "\t.def\tprintf;\t.sc"
   "l\t3;\t.type\t32;\t."
   "endef\n"
   "\t.seh_proc\tprintf"
   "\n"
   "printf:\n"
   "\tpushq\t%%rbp\n"
   "\t.seh_pushreg\t%%rbp"
   "\n"
   "\tpushq\t%%rbx\n"
   "\t.seh_pushreg\t%%rbx"
   "\n"
   "\tsubq\t$56, %%rsp\n"
   ""
   "\t.seh_stackalloc\t5"
   "6\n"
   "\tleaq\t48(%%rsp), %%r"
   "bp\n"
   "\t.seh_setframe\t%%rb"
   "p, 48\n"
   "\t.seh_endprologue\n"
   ""
   "\tmovq\t%%rcx, 32(%%rb"
   "p)\n"
   "\tmovq\t%%rdx, 40(%%rb"
   "p)\n"
   "\tmovq\t%%r8, 48(%%rbp"
   ")\n"
   "\tmovq\t%%r9, 56(%%rbp"
   ")\n"
   "\tleaq\t40(%%rbp), %%r"
   "ax\n"
   "\tmovq\t%%rax, -16(%%r"
   "bp)\n"
   "\tmovq\t-16(%%rbp), %%"
   "rbx\n"
   "\tmovl\t$1, %%ecx\n"
   "\tmovq\t__imp___acrt"
   "_iob_func(%%rip), %%ra"
   "x\n"
   "\tcall\t*%%rax\n"
   "\tmovq\t%%rbx, %%r8\n"
   ""
   "\tmovq\t32(%%rbp), %%r"
   "dx\n"
   "\tmovq\t%%rax, %%rcx\n"
   ""
   "\tcall\t__mingw_vfpr"
   "intf\n"
   "\tmovl\t%%eax, -4(%%rb"
   "p)\n"
   "\tmovl\t-4(%%rbp), %%e"
   "ax\n"
   "\taddq\t$56, %%rsp\n"
   ""
   "\tpopq\t%%rbx\n"
   "\tpopq\t%%rbp\n"
   "\tret\n"
   "\t.seh_endproc\n";